name: installed_apps
description: Flutter plugin with utility methods related to installed apps on device.
version: 1.6.0
homepage: https://github.com/RevEngiSquad/installed_apps.git
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: org.revengi.installed_apps
        pluginClass: InstalledAppsPlugin
